# constants
ERROR_USER_NOT_FOUND = "Error: User not found."
ERROR_NO_USERS_FOUND = "Error: No Users Found."
ERROR_CAR_NOT_FOUND = "Error: Car not found."
ERROR_NO_CARS_FOUND = "Error: No Cars Found."
ERROR_SERVICE_NOT_FOUND = "Error: Service not found."
ERROR_NO_SERVICES_FOUND = "Error: No Services Found."
ERROR_PLEASE_LOG_IN = "Error: Please log in."
ERROR_FETCHING_DATA = "Error: fetching data"
EXPORT_CSV_MESSAGE = "*** FOR FULL DETAILS, EXPORT TO A CSV FILE! ***"